### ISSUE TITLE
Migration not working with Postgres

### ISSUE THREAD

**Issue by giudax18** [dereuromark/cakephp-queue#213]
Hi, trying to install this plugin.
The migration script gave me these errors from Phinx, I'm using Postgres:

```sh
$ bin/cake migrations migrate -p Queue
using migration paths
 - /vendor/dereuromark/cakephp-queue/config/Migrations
using seed paths
 - /vendor/dereuromark/cakephp-queue/config/Seeds
using environment default
using adapter pgsql
using database cakecms

[...]

'SQLSTATE[42601]: Syntax error: 7 ERROR:  type modifier not allowed for the type "text"'

[...]

 == 20171013131845 AlterQueuedJobs: migrating

'SQLSTATE[42601]: Syntax error: 7 ERROR:  type modifier not allowed for the type "text"'

 == 20171013131845 AlterQueuedJobs: migrated 0.0107s

 == 20171013133145 Utf8mb4Fix: migrating
Exception: SQLSTATE[42601]: Syntax error: 7 ERROR:  type modifier not allowed for the type "text" in [/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php, line 338]
2019-01-17 08:33:26 Error: [PDOException] SQLSTATE[42601]: Syntax error: 7 ERROR:  type modifier not allowed for the type "text" in /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php on line 338                                                                    

 == 20171019083502 MigrationQueueStatus: migrating
Exception: SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  the column "terminate" is type boolean but the default expression is of type integer
HINT:  You must rewrite or convert the type of the expression into
 [/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php, line 338]
```
I applyed some fast fix to this, hope this can be applyed to the project in someway:

/cakephp-queue/config/Migrations/20171019083502_MigrationQueueStatus.php
```
	public function change() {
		$this->table('queue_processes')
			->addColumn('terminate', 'boolean', [
				'default' => FALSE,
				'null' => false,
			])
			->update();
```

Here we need a proper limit parameter, but for now I commented out the row

/cakephp-queue/config/Migrations/20171013133145_Utf8mb4Fix.php
```
		$table->changeColumn('data', 'string', [
//			'limit' => MysqlAdapter::TEXT_MEDIUM,
			'null' => true,
			'default' => null,
			'encoding' => 'utf8mb4',
			'collation' => 'utf8mb4_unicode_ci',
		]);

		$table->changeColumn('failure_message', 'string', [
//			'limit' => MysqlAdapter::TEXT_MEDIUM,
			'null' => true,
			'default' => null,
			'encoding' => 'utf8mb4',
			'collation' => 'utf8mb4_unicode_ci',
		]);
```

**Comment by dereuromark** [comment]
i see. we need to set this conditinally then

**Comment by dereuromark** [comment]
i see. we need to set this conditinally then

**Comment by giudax18** [comment]
Poking around with the code, I made a little snippet that partially enable the dynamic retrieve of the current db adapter (inherited from Cake).
Hope this can help you for future works.

```php
		try {
                    $adapterFactory = new \Phinx\Db\Adapter\AdapterFactory();
                    $adapter = $adapterFactory->getAdapter($this->getAdapter()->getAdapterType(), []);
                    $type = $adapter->getSqlType('text', 'mediumtext');

                    $limit = 255;
                        
			if ($type["name"]) {
				$table->changeColumn('failure_message', "string", [
					'limit' => $limit,
					'null' => true,
					'default' => null,
				]);

				$table->save();
			}
		} catch (Exception $e) {
			Debugger::dump($e->getMessage());
		}
```

**Comment by dereuromark** [comment]
I like it
Would you be able to PR this into the ones in question?
This could also be trait and method to be reused: getSqlType() or alike

Not sure if we need the try catch here though then.

**Comment by dereuromark** [comment]
ping @giudax18

**Comment by dereuromark** [comment]
Refs https://github.com/dereuromark/cakephp-queue/pull/218

**Comment by dereuromark** [comment]
Resolved for now using try/catch

**Comment by mstroink** [comment]
I'm still getting this error. Probably because you need to call save(). Not sure yet.

`
'SQLSTATE[42601]: Syntax error: 7 ERROR:  type modifier is not allowed for type "text"'

RuntimeException: Migration has pending actions after execution! in /Applications/MAMP/htdocs/projects/my_app/vendor/robmorgan/phinx/src/Phinx/Migration/AbstractMigration.php:362
Stack trace:
#0 /Applications/MAMP/htdocs/projects/my_app/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(390): Phinx\Migration\AbstractMigration->postFlightCheck('up')
#1 /Applications/MAMP/htdocs/projects/my_app/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(361): Phinx\Migration\Manager->executeMigration('default', Object(IncreaseDataSize), 'up', false)
#2 /Applications/MAMP/htdocs/projects/my_app/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('default', 20171019083506, false)
#3 /Applications/MAMP/htdocs/projects/my_app/vendor/cakephp/migrations/src/Command/CommandTrait.php(35): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Applications/MAMP/htdocs/projects/my_app/vendor/cakephp/migrations/src/Command/Migrate.php(67): Migrations\Command\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Applications/MAMP/htdocs/projects/my_app/vendor/symfony/console/Command/Command.php(255): Migrations\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Applications/MAMP/htdocs/projects/my_app/vendor/symfony/console/Application.php(921): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Applications/MAMP/htdocs/projects/my_app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Applications/MAMP/htdocs/projects/my_app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Applications/MAMP/htdocs/projects/my_app/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Applications/MAMP/htdocs/projects/my_app/vendor/cakephp/cakephp/src/Console/Shell.php(532): Migrations\Shell\MigrationsShell->main('migrations', 'migrate')
#11 /Applications/MAMP/htdocs/projects/my_app/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(164): Cake\Console\Shell->runCommand(Array, true, Array)
#12 /Applications/MAMP/htdocs/projects/my_app/vendor/cakephp/cakephp/src/Console/CommandRunner.php(384): Migrations\Shell\MigrationsShell->runCommand(Array, true)
#13 /Applications/MAMP/htdocs/projects/my_app/vendor/cakephp/cakephp/src/Console/CommandRunner.php(162): Cake\Console\CommandRunner->runShell(Object(Migrations\Shell\MigrationsShell), Array)
#14 /Applications/MAMP/htdocs/projects/my_app/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#15 {main}`

**Comment by dereuromark** [comment]
Can u make a PR that fixes things?

**Comment by mstroink** [comment]
I don't have a fix at the moment. I think we have to check on adapter type instead of try/catch. 
Try/Catch doesn't prevent pending actions after execution.

Something like:
```php
	public function change() {
		$table = $this->table('queued_tasks');

		if ($this->getAdapter()->getAdapterType() == 'mysql') {
			$adapter = new MysqlAdapter([]);
			if ($adapter->getSqlType('text', 'longtext')) {
				$table->changeColumn('data', 'text', [
					'limit' => MysqlAdapter::TEXT_LONG,
					'null' => true,
					'default' => null,
				]);
			}
		}

		$table->save();
	}
```
